version: 0.2            
phases:
  install:
    runtime-versions:
      nodejs: 22.x
    commands:
      - echo 'DONE'
  pre_build:
    commands:
      - npm install
      - echo 'DONE'
  build:
    commands:
      - npm run build
      - echo 'DONE'
  post_build:
    commands:
      - echo 'DONE'
artifacts:
  files:
    - "**/*"
  base-directory: ./dist